# name: My first workflow
# on: push
# jobs:
#   say-hello:
#     runs-on: ubuntu-latest
#     steps:
#       - name:  Print message
#         run: echo "Hello, github Actions!"
#   say-byee:
#     runs-on: ubuntu-latest
#     steps:
#       - name:  Print message
#         run: echo "Bye, github Actions!"

name: My first workflow
on: push
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name:  Print message
        run: echo "Hello, github Actions!"
  say-byee:
  needs: say-hello
    runs-on: ubuntu-latest
    steps:
      - name:  Print message
        run: echo "Bye, github Actions!"